version: "3.8"
services:

  sim_combat_server:
    build: ./simcombat-service
    image: simcombat_service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db_sim_combat
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db_sim_combat
      MYSQL_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://db_sim_combat:3306/sim_combat?createIfDatabaseNotExist=true
    depends_on:
      db_sim_combat:
        condition: service_healthy

  db_sim_combat:
    container_name: db_sim_combat
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: sim_combat
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
